### ISSUE TITLE
Survive not having an .m2/settings.xml file

### ISSUE THREAD

**Issue by dwalend** [sbt/sbt-pom-reader#19]
Right out of the gate I got

> test
[trace] Stack trace suppressed: run last *:credentials for the full output.
[error] (*:credentials) java.io.FileNotFoundException: /Users/david/.m2/settings.xml (No such file or directory)
[error] Total time: 0 s, completed Feb 2, 2015 4:50:49 PM

I got past the problem by dropping the empty one from http://maven.apache.org/settings.html in the right spot, and am now chasing down our code base's dependencies.

Thanks,

Dave

**Comment by metasim** [comment]
@jsuereth I think 22174a89421c08ee4cfa65b69876e6f9891f5682  addressed this one. I was able to run all the scripted tests without a `settings.xml` file.

**Comment by metasim** [comment]
Fixed in v2.0.0
