### ISSUE TITLE
Dependencies not pulled when they have classifiers.

### ISSUE THREAD

**Issue by varuns-zetaris** [sbt/sbt-pom-reader#37]
pom reader fails to resolve dependencies when they are of the format :  

```
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql_2.10</artifactId>
        <version>${spark.version}</version>
        <type>test-jar</type>
        <scope>test</scope>
    </dependency>
```

When you add a classifier - <type> the plugin fails to load the dependency

**Comment by metasim** [comment]
@varuns-zetaris I'm not sure this is a bug. In my understanding of Maven coordinates `<type>test-jar</type>` wouldn't be considered (by default) a classpath-loaded dependency. If you change `type` to `jar` does it work?

**Comment by metasim** [comment]
@varuns-zetaris To be technically precise, your example isn't showing the use of a maven `classifier` coordinate. See [here](http://maven.apache.org/pom.html#Dependencies) for details on the differences between `classifier`, `type`, and `scope`.
