### ISSUE TITLE
Plugins' dependencies seem outdated

### ISSUE THREAD

**Issue by jvican** [sbt/sbt-pom-reader#44]
These plugins' dependencies are in conflict with scalafmt's sbt plugin, and seem outdated. The issue seems to be triggered by a transitive dependency of aether and the rest of dependencies of this plugin.

```
[error] java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
[error]         at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$.$anonfun$buildSettings$5(ScalafmtCorePlugin.scala:246)
[error]         at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:804)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:197)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:214)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:159)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:82)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:93)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:89)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
```
  
There's no workaround to this. This plugin cannot be used with scalafmt's plugin.

**Comment by metasim** [comment]
@jvican This plugin needs contributors. Care to submit some PRs for these issues?

**Comment by jvican** [comment]
Sorry, I don't have the time for submitting a PR.

**Comment by jvican** [comment]
For some progress on this, see https://github.com/scalacenter/sbt-pom-reader/commit/f13c8531a77d13d19bb64ae667c9926abae4ca5e and its commit message.

**Comment by gemelen** [comment]
Could be closed.

**Comment by SethTisue** [comment]
@gemelen you've tried using the two plugins in the same project recently and there was no conflict?

**Comment by gemelen** [comment]
@SethTisue yes. [This comment](https://github.com/sbt/sbt-pom-reader/issues/44#issuecomment-356126508) uses demonstrates part of a solution that is incorporated in latest dependencies upgrade (ie https://github.com/sbt/sbt-pom-reader/pull/70/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R20 ).
But to double check I've added Scalafmt plugin into this project tests and run them without any issue relevant to current one.
