### ISSUE TITLE
CI requires migration

### ISSUE THREAD

**Issue by gemelen** [sbt/sbt-pom-reader#67]
Current setup is behind current situation with Travis changes, bintray changes and possibe some more.

Minimum list of issues to solve:
1. how to build without pulling versions from Bintray (current setup looks there and fails)
2. where to publish result artifact and what else needs to be configured to do so

**Comment by gemelen** [comment]
@eed3si9n could you please advise how to configure this repo according the issues?

Is it viable to switch to GH Actions for the first one?

**Comment by eed3si9n** [comment]
Not sure what you mean by "pulling versions from Bintray"

**Comment by gemelen** [comment]
If I undesrtand logs for https://travis-ci.org/github/sbt/sbt-pom-reader/builds/766704469 run correctly, travis tries to fetch latest SBT from https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt which in interactive mode redirects me to https://dl.bintray.com/sbt/maven-releases/org/scala-sbt/ (where latest sbt versions are not present)

**Comment by eed3si9n** [comment]
That's actually a bug in Travis CI using an older version sbt-extras - https://github.com/sbt/sbt/discussions/6441

You can mitigate this by migrating to GitHub Actions, bumping to more recent sbt-extras, or using the official sbt.
