### ISSUE TITLE
Travis CI is dropped

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-pom-reader#68]
Given the poor handling of the recent security incident (https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/) I'm suspending Travis CI integration indefinitely.

Let's move on to GitHub Actions.

**Comment by gemelen** [comment]
#69 as an attempt to do so. Please review when any of you maintainers would have time.

**Comment by blast-hardcheese** [comment]
Merged, thank you for your work here @gemelen
