### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by felipepessoto** [sbt/sbt-pom-reader#75]
It seems it doesn't work anymore since it throws an 501 error because it tries to access http://repo.maven.apache.org/maven2 at https://github.com/sbt/sbt-pom-reader/blob/938fa220b0bc2053a251a669b8c5c90b5d1d8415/src/main/scala/com/typesafe/sbt/pom/MavenPomResolver.scala#L60

**Comment by gemelen** [comment]
Hi @felipepessoto 
No, it's not active (you may already found that by the lack of response in your and similar PR on updating link to HTTPS). However, it's still in use.

We may ping @jsuereth and @eed3si9n for the sake of keeping it running, I guess. However, before you PR https://github.com/sbt/sbt-pom-reader/pull/74 could be merged you would need to accept Lightbend Contributors License Agreement.

**Comment by eed3si9n** [comment]
For the purpose of open source community there's already Coursier, I don't see a strong need to keep this plugin active.
For corporate users, maybe there are various reasons to tweak the external dependency resolution, and might be motivated to keep this plugin going. I'd be happy to add anyone interested as a maintainer, but I'm not really invested in playing the role for this plugin.

**Comment by gemelen** [comment]
@eed3si9n this plugin is vital for Apache Spark build.

**Comment by eed3si9n** [comment]
@gemelen I invited you to https://github.com/orgs/sbt/teams/sbt-pom-reader team, which should give you write rights to this repo.

**Comment by felipepessoto** [comment]
> Hi @felipepessoto No, it's not active (you may already found that by the lack of response in your and similar PR on updating link to HTTPS). However, it's still in use.
> 
> We may ping @jsuereth and @eed3si9n for the sake of keeping it running, I guess. However, before you PR #74 could be merged you would need to accept Lightbend Contributors License Agreement.

Reviewing and get approval of a custom CLA will take a lot of time and effort from legal team. I closed the PR.

**Comment by HyukjinKwon** [comment]
At least this is being used in several projects e.g., Apache Spark.

**Comment by gemelen** [comment]
> > Hi @felipepessoto No, it's not active (you may already found that by the lack of response in your and similar PR on updating link to HTTPS). However, it's still in use.
> > We may ping @jsuereth and @eed3si9n for the sake of keeping it running, I guess. However, before you PR #74 could be merged you would need to accept Lightbend Contributors License Agreement.
> 
> Reviewing and get approval of a custom CLA will take a lot of time and effort from legal team. I closed the PR.

I'll take care about this from here. Thanks for raising the issue once more.
